[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["uuid", "json"] }
serde = "1.0.193"
uuid = { version = "1.6.1", features = [ "v7"] }

